//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Remont
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_Order { get; set; }
        public int Client_ID { get; set; }
        public int Equipment_ID { get; set; }
        public int Status_ID { get; set; }
        public int Employee_ID { get; set; }
        public int Part_ID { get; set; }
        public int EquipmentType_ID { get; set; }
        public string Descriptionn { get; set; }
        public string ReceptionDate { get; set; }
        public decimal RepairCost { get; set; }
        public string NumberOrder { get; set; }
    
        public virtual Clients Clients {  get; set; }
        public virtual Employees Employees {  get; set; }
        public virtual Equipments Equipments {  get; set; }
        public virtual EquipmentTypes EquipmentTypes {  get; set; }
        public virtual SpareParts SpareParts {  get; set; }
        public virtual Statuses Statuses {  get; set; }
    }
}
